{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "names.fullname" . }}
spec:
  schedule: {{ .Values.cron.schedule | default "*/30 * * * *" | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drupal-cron
            image: "byrnedo/alpine-curl:0.1"
            args:
            - -ks
            - {{ .Values.cron.url }}
          restartPolicy: OnFailure
{{- end }}
